
version: 2

sources:
  - name: sf_source_tables
    database: CADS_ARCHITECTURE
    schema: SNFK_ACCOUNT_USAGE
    tables:
      - name: USERS
      - name: WAREHOUSE_METERING_HISTORY
      - name: ACCESS_HISTORY
      - name: TABLES
      - name: VIEWS
      - name: GRANTS_TO_USERS
      - name: ROLES
      - name: QUERY_HISTORY
